#!/bin/bash
# Provider Dashboard Testing Script
# Use this with Postman or curl to test the endpoints

BASE_URL="http://localhost:8080/api"
JWT_TOKEN="YOUR_JWT_TOKEN_HERE"

echo "========================================="
echo "Provider Dashboard Endpoint Testing"
echo "========================================="
echo ""

echo "1. First, login as a provider to get JWT token:"
echo "POST $BASE_URL/users/login"
echo "Body: { \"email\": \"provider@esprit.tn\", \"password\": \"yourpassword\" }"
echo ""
echo "Copy the token from response and set it below:"
echo "JWT_TOKEN=\"eyJhbGciOiJIUzI1...\""
echo ""

echo "2. Test GET /api/provider/orders"
echo "curl -X GET \"$BASE_URL/provider/orders\" \\"
echo "  -H \"Authorization: Bearer \$JWT_TOKEN\" \\"
echo "  -H \"Content-Type: application/json\""
echo ""
echo "Expected: 200 OK with array of orders (can be empty)"
echo ""

echo "3. Test GET /api/provider/statistics"
echo "curl -X GET \"$BASE_URL/provider/statistics\" \\"
echo "  -H \"Authorization: Bearer \$JWT_TOKEN\" \\"
echo "  -H \"Content-Type: application/json\""
echo ""
echo "Expected: 200 OK with statistics object"
echo ""

echo "4. Test PUT /api/provider/orders/{orderId}/status"
echo "curl -X PUT \"$BASE_URL/provider/orders/ORDER_ID_HERE/status?newStatus=CONFIRMED\" \\"
echo "  -H \"Authorization: Bearer \$JWT_TOKEN\" \\"
echo "  -H \"Content-Type: application/json\""
echo ""
echo "Expected: 200 OK with updated order"
echo "         404 if order not found"
echo "         403 if not authorized"
echo ""

echo "========================================="
echo "Frontend Testing Steps"
echo "========================================="
echo ""
echo "1. Start frontend: cd frontend && npm start"
echo "2. Navigate to: http://localhost:4200/provider-dashboard"
echo "3. Login with provider credentials"
echo "4. Check browser console for:"
echo "   - ✅ Provider Dashboard initialized"
echo "   - 📊 Loading provider orders..."
echo "   - ✅ Orders loaded: [...]"
echo "5. Verify orders table displays correctly"
echo "6. Test Confirm/Cancel buttons"
echo ""

echo "========================================="
echo "Debugging Checklist"
echo "========================================="
echo ""
echo "If orders don't appear, check:"
echo "☐ Provider has a shop (db.shops.findOne({ ownerId: ObjectId('...') }))"
echo "☐ Shop has products (db.products.find({ shopId: ObjectId('...') }))"
echo "☐ Orders exist with those products (db.cart_items.find({ productId: { \$in: [...] } }))"
echo "☐ Backend logs show: 🔍 DEBUG: Provider products count: X (X > 0)"
echo "☐ Backend logs show: 🔍 DEBUG: Final provider orders count: X (X > 0)"
echo ""

echo "If statistics are wrong, check:"
echo "☐ Backend logs: 🔍 STATS: Provider orders: X"
echo "☐ Backend logs: 🔍 STATS: Total revenue: Y"
echo "☐ Verify order status is CONFIRMED/DELIVERED/SHIPPED for revenue"
echo ""

echo "========================================="
echo "MongoDB Queries for Manual Verification"
echo "========================================="
echo ""
echo "// Find provider's shop"
echo "db.shops.findOne({ ownerId: ObjectId('PROVIDER_ID') })"
echo ""
echo "// Find shop's products"
echo "db.products.find({ shopId: ObjectId('SHOP_ID') })"
echo ""
echo "// Find orders containing those products"
echo "db.cart_items.find({ productId: { \$in: [ObjectId('PRODUCT1'), ObjectId('PRODUCT2')] } })"
echo ""
echo "// Get full order details"
echo "db.carts.find({ _id: { \$in: [ObjectId('CART1'), ObjectId('CART2')] } })"
echo ""
