@echo off
cd ml-service
if not exist venv (
    echo Creating virtual environment...
    python -m venv venv
)
echo Activating virtual environment...
call venv\Scripts\activate
echo Installing dependencies...
pip install -r requirements.txt
echo Starting ML Prediction Service on port 8000...
uvicorn main:app --host 0.0.0.0 --port 8000
pause
